---

namespace: bodsch
name: grafana

version: 1.0.2
readme: README.md

authors:
  - Bodo Schulz (@bodsch)

description: A collection of Ansible roles for the Grafana universe.

license:
  - Apache-2.0

license_file: ''

tags:
  - monitoring
  - grafana
  - observability

dependencies:
  bodsch.core: ">=2.2.1"
  # bodsch.scm: "*"
  community.grafana: "*"

repository: https://github.com/bodsch/ansible-collection-grafana
documentation: https://github.com/bodsch/ansible-collection-grafana/README.md
homepage: https://github.com/bodsch/ansible-collection-grafana
issues: https://github.com/bodsch/ansible-collection-grafana/issues

build_ignore:
  - "galaxy.yml"
  - "*.pyc"
  - "*.retry"
  - ".ansible-lint"
  - ".editorconfig"
  - ".flake8"
  - ".gitignore"
  - ".yamllint"
  - ".github"
