---

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - promtail_version == "latest"
  block:
    - name: get latest release
      delegate_to: localhost
      become: false
      run_once: true
      bodsch.scm.github_latest:
        project: grafana
        repository: loki
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        github_tags: "{{ promtail_scm.use_tags | default('false') }}"
        without_beta: "{{ promtail_scm.without_beta | default('false') }}"
        filter_elements: "{{ promtail_scm.version_filter | default([]) }}"
      register: _latest_release

    - name: re-define promtail_version
      ansible.builtin.set_fact:
        promtail_version: "{{ _latest_release.latest_release }}"

- name: define download information
  ansible.builtin.set_fact:
    promtail_release: "{{ promtail_defaults_release | combine(promtail_release, recursive=True) }}"

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    promtail_delegate_to: "{{ ansible_host }}"
    promtail_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/promtail', true) }}/{{ promtail_version }}"
  when:
    - promtail_direct_download

- name: create download directory
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ promtail_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: detect the downloaded promtail archive
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ promtail_local_tmp_directory }}/{{ promtail_release.file }}"
  register: stat_promtail_archive

- name: download
  when:
    - stat_promtail_archive.stat is defined
    - not stat_promtail_archive.stat.exists | default('false')
  block:
    - name: checksum
      become: false
      delegate_to: localhost
      run_once: true
      block:
        - name: get checksum list
          bodsch.scm.github_checksum:
            project: grafana
            repository: loki
            checksum_file: SHA256SUMS
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
            architecture: "{{ ansible_architecture }}"
            system: "{{ ansible_facts.system }}"
            version: "v{{ promtail_version }}"
          register: _latest_checksum

        - name: define checksum for {{ go_arch }} architecture
          ansible.builtin.set_fact:
            __promtail_checksum: "sha256:{{ _latest_checksum.checksums | bodsch.grafana.promtail_checksum('promtail', ansible_facts.system | lower, system_architecture) }}"
          when:
            - _latest_checksum.rc == 0
            - _latest_checksum.checksum is defined
            - _latest_checksum.checksum | string | length > 0

    - name: download promtail binary archive
      become: false
      delegate_to: "{{ promtail_delegate_to }}"
      run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ promtail_release_download_url }}/download/v{{ promtail_version }}/{{ promtail_release.file }}"
        dest: "{{ promtail_local_tmp_directory }}/{{ promtail_release.file }}"
        checksum: "{{ __promtail_checksum | default(omit) }}"
        mode: 0644
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ promtail_delegate_to }}"
      run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ promtail_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect extracted binary
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ promtail_local_tmp_directory }}/{{ promtail_release.binary }}-{{ ansible_facts.system | lower }}-{{ system_architecture }}"
  register: stat_promtail_binary

- name: extract promtail archive
  become: false
  delegate_to: "{{ promtail_delegate_to }}"
  run_once: "{{ 'false' if promtail_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ promtail_local_tmp_directory }}/{{ promtail_release.file }}"
    dest: "{{ promtail_local_tmp_directory }}/"
    copy: false
  when:
    - stat_promtail_binary.stat is defined
    - not stat_promtail_binary.stat.exists | default('false')

...
