---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: install dependency
  ansible.builtin.package:
    name: "{{ promtail_requirements }}"
    state: present

# - name: detect our installation path
#   ansible.builtin.stat:
#     path: "{{ promtail_install_path | dirname }}"
#     get_checksum: false
#   register: stat_promtail_path
#   ignore_errors: true
#
# - name: old installation
#   when:
#     - stat_promtail_path is defined
#     - stat_promtail_path.stat is defined
#     - stat_promtail_path.stat.isdir is defined
#     - not stat_promtail_path.stat.isdir
#   block:
#     - name: stop old service
#       ansible.builtin.service:
#         name: promtail
#         state: stopped
#         enabled: false
#
#     - name: remove installed systemd unit
#       ansible.builtin.file:
#         state: absent
#         path: /etc/systemd/system/promtail.service
#
#     - name: remove installed promtail
#       ansible.builtin.file:
#         state: absent
#         path: "{{ stat_promtail_path.stat.path }}"
#
# - name: flush handlers
#   ansible.builtin.meta: flush_handlers

- name: merge promtail configuration between defaults and custom
  ansible.builtin.set_fact:
    promtail_runtime: "{{ promtail_defaults_runtime | combine(promtail_runtime, recursive=True) }}"
    promtail_systemd: "{{ promtail_defaults_systemd | combine(promtail_systemd, recursive=True) }}"
    promtail_server: "{{ promtail_defaults_server | combine(promtail_server, recursive=True) }}"
    promtail_clients: "{{ promtail_defaults_clients | union(promtail_clients) }}"
    promtail_positions: "{{ promtail_defaults_positions | combine(promtail_positions, recursive=True) }}"
    promtail_targets: "{{ promtail_defaults_targets | combine(promtail_targets, recursive=True) }}"
    promtail_limits: "{{ promtail_defaults_limits | combine(promtail_limits, recursive=True) }}"
    promtail_tracing: "{{ promtail_defaults_tracing | combine(promtail_tracing, recursive=True) }}"

- name: fail when client are missing
  ansible.builtin.fail:
    msg: "least one client config should be provided"
  when:
    - promtail_clients | default([]) | count == 0

...
