---

- name: converge
  hosts: instance
  any_errors_fatal: false
  become: false

  environment:
    NETRC: ''

  roles:
    # - role: bodsch.grafana.promtail
    #   vars:
    #     promtail_version: "2.7.2"

    - role: bodsch.grafana.promtail
