---

- name: install grafana plugins
  grafana_plugins:
    command: install
    plugins_dir: "{{ grafana_data_dir }}/plugins"
    plugins: "{{ grafana_plugins }}"
  register: install_plugins
  notify:
    - restart grafana
    - information about grafana plugins

# - name: information about grafana plugins
#   ansible.builtin.debug:
#     msg: "{{ install_plugins.msg }}"
#   when:
#     - install_plugins is defined
#     - install_plugins.msg is defined

...
