---

nginx_vhosts: "{{
  nginx_vhosts_default |
  union(nginx_vhosts_redirects) |
  union(nginx_vhosts_base | default([])) }}"


nginx_vhosts_default:

  - name: default
    enabled: false
    description: |
      simply a default vhost
    ssl:
      enabled: false

  - name: nginx-status
    filename: 00-status.conf
    state: present  # default: present
    enabled: true   # default: true
    # domain(s)
    domains:
      - localhost
    # listen
    listen:
      - 127.0.0.1:8088

    root_directory: /var/www/

    # locations
    locations:
      "/nginx_status":
        options: |
          stub_status on;
          access_log off;
          allow 127.0.0.1;
          deny all;

nginx_vhosts_redirects:

  - name: 01.docker.local
    filename: 10-01.docker.local.conf
    state: present
    enabled: true

    listen: 80
    domains:
      - 01.docker.local

    root_directory: /var/www/01.docker.local
    root_directory_create: True

    logfiles: {}

    locations:
      "^~ /":
        options: |
          return 301 https://molecule.docker.local/01.html;

  - name: 02.docker.local
    filename: 10-02.docker.local.conf
    state: present
    enabled: false

    listen: 80
    domains:
      - 02.docker.local

    root_directory: /var/www/02.docker.local

    locations:
      "^~ /":
        options: |
          return 301 https://molecule.docker.local/02.html;

  - name: 20-foo.docker.local
    filename: 20-foo.docker.local.conf
    state: absent
    enabled: true

    domains:
      - foo.docker.local

    listen: 80

    root:  /var/www/foo.docker.local

    logfiles:
      access:
        file: /var/log/nginx/foo.docker.local/access.log
        # loglevel: 'json_analytics'
      error:
        file: /var/log/nginx/foo.docker.local/error.log
        loglevel: notice

    # list of upstream servers
    upstreams:
      - name: paperless
        servers:
          - 127.0.0.1:8080   max_fails=3 fail_timeout=30s
        # strategy: 'ip_hash'
        keepalive: 32
      - name: unifi
        servers:
          - 127.0.0.1:8090   max_fails=3 fail_timeout=30s
        # strategy: 'ip_hash'
        keepalive: 32

    locations:
      "^~ /":
        options: |
          add_header X-Backend "bar";

          proxy_pass         http://paperless/;
          proxy_set_header   Host              $host;
          proxy_set_header   X-Real-IP         $remote_addr;
          proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;

  - name: 40-foo.docker.local
    filename: 40-foo.docker.local.conf
    state: present
    enabled: false

    domains:
      - foo.docker.local

    listen:
      - 443 ssl http2

    # enable ssl
    ssl:
      enabled: true
      ciphers: default
      certificate:     /etc/snakeoil/docker.local/docker.local.pem
      certificate_key: /etc/snakeoil/docker.local/docker.local.pem

...
