---

snakeoil_extract_to: /etc/snakeoil

snakeoil_domain: docker.local

snakeoil_life_time: 30

snakeoil_dhparam: 2048

snakeoil_alt_names:
  - dns:
      - "docker.local"
      - "www.docker.local"
      - molecule.docker.local

...
