---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: information
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
          - "ansible_service_mgr  : {{ ansible_service_mgr }}"

- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      when:
        - ansible_distribution | lower == 'archlinux' or
          ansible_os_family | lower == 'artix linux'
      block:
        - name: update pacman system
          ansible.builtin.command: |
            pacman --refresh --sync --sysupgrade --noconfirm

        - name: create depends service
          ansible.builtin.copy:
            mode: 0755
            dest: /etc/init.d/net
            content: |
              #!/usr/bin/openrc-run
              true
          when:
            - ansible_os_family | lower == 'artix linux'

    - name: update package cache
      ansible.builtin.package:
        update_cache: true

    - name: install pip
      when:
        - ansible_distribution | lower == 'debian'
      block:
        - name: install python3-pip
          ansible.builtin.package:
            name: python3-pip
            state: present

- name: prepare all
  hosts: all
  gather_facts: true

  roles:
    # - role: apparmor
    - role: snapd

- name: prepare nginx
  hosts: nginx
  gather_facts: true

  pre_tasks:
    - name: do facts module to get latest information
      ansible.builtin.setup:
        gather_subset:
          - 'all'

  roles:
    - role: snakeoil
    - role: nginx

- name: prepare influxdb
  hosts: influxdb
  gather_facts: true

  pre_tasks:
    # to fix https://github.com/mkayontour/ansible-influxdb/issues/9
    - name: add influxdata-archive_compat.key
      shell:
        cd /tmp/ ;
        curl https://repos.influxdata.com/influxdata-archive_compat.key > /tmp/influxdata-archive_compat.key &&
        echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c /tmp/influxdata-archive_compat.key' | sha256sum -c && cat /tmp/influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg
      when:
        - ansible_distribution | lower == 'debian'

  roles:
    - role: influxdb

- name: prepare prometheus
  hosts: prometheus
  gather_facts: true
  roles:
    - role: bodsch.prometheus.prometheus

- name: prepare ldap
  hosts: auth
  gather_facts: true

  roles:
    - role: glauth

- name: prepare database
  hosts: database
  gather_facts: true

  roles:
    - role: syslog-ng
    - role: mariadb
    - role: redis

...
