---

- name: snapd
  src: https://github.com/bodsch/ansible-snapd
  version: 1.3.1

- name: nginx
  src: https://github.com/bodsch/ansible-nginx
  scm: git
  version: 0.27.2

- name: redis
  src: https://github.com/bodsch/ansible-redis
  version: 1.4.1

- name: mariadb
  src: https://github.com/bodsch/ansible-mariadb
  version: 2.6.0

- name: influx2
  src: https://github.com/bodsch/ansible-influxdb
  version: 1.3.1

- name: influxdb
  src: mkayontour.influxdb
  src: https://github.com/mkayontour/ansible-influxdb.git
  scm: git

- name: glauth
  src: https://github.com/bodsch/ansible-glauth
  version: 1.6.2

...
