---

galaxy_info:
  role_name: grafana

  author: Bodo Schulz
  description: ansible role to setup grafana
  license: Apache
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
        - bookworm

  galaxy_tags:
    - grafana
    - monitoring
    - graphing

dependencies: []

...
