---

- name: detect our installation path '{{ loki_install_path | dirname }}'
  ansible.builtin.stat:
    path: "{{ loki_install_path | dirname }}"
    get_checksum: false
  register: stat_loki_path
  ignore_errors: true

- name: old installation
  when:
    - stat_loki_path is defined
    - stat_loki_path.stat is defined
    - stat_loki_path.stat.isdir is defined
    - not stat_loki_path.stat.isdir
  block:
    - name: stop old service
      ansible.builtin.service:
        name: loki
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: remove installed systemd unit
      ansible.builtin.file:
        state: absent
        path: /etc/systemd/system/loki.service
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: remove installed loki
      ansible.builtin.file:
        state: absent
        path: "{{ stat_loki_path.stat.path }}"

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
